[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"
gas_reports = ["*"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

[linter]
enabled = true
